language: python
python:
  - "3.5"

env:
  global:
    - GIT_NAME: BlogA Demo
    - GIT_EMAIL: richardchienthebest@gmail.com
    - GITHUB_REPO: BlogTANG/blog-a-demo
    - GIT_SOURCE: _deploy

before_install:
  - nvm install 4

# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script:
  - python app.py apply-theme
  - python app.py generate

after_success:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm install git-update-ghpages && ./node_modules/.bin/git-update-ghpages -e; fi
