language: python
python:
  - "3.4"
  - "3.5"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script:
  - "python app.py apply-theme"
  - "python app.py generate"
  - "python app.py clean"
